import React from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import TRANSLATION from '@/locale';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Talent Flow',
  description: 'Generated by create next app',
  icons: {
    icon: { url: '/favicon.ico', type: 'image/svg' },
  },
};

interface IProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: IProps) {
  const { layout } = TRANSLATION;
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <div className="bg-gray-100 min-h-screen flex flex-col justify-between overflow-y-hidden">
          <header className="py-6 bg-white">
            <nav className="container mx-auto px-4 flex items-center justify-between">
              <Link href="/">
                <div className="flex flex-row justify-center items-start gap-1">
                  <Image alt="tf-icon" src="/logo.svg" width={30} height={30} />
                  <h1 className="text-2xl font-bold text-blue-900">{layout.talentFlow}</h1>
                </div>
              </Link>
            </nav>
          </header>
          <main className="flex justify-center flex-1 h-full container mx-auto px-4 py-8">
            {children}
          </main>
          <footer className="bg-gray-200 py-4 text-center">
            <p className="text-gray-600">{layout.footer}</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
